# Generated by Django 4.1.6 on 2023-02-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='banner_link',
        ),
        migrations.AddField(
            model_name='banner',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
