# Generated by Django 4.1.6 on 2023-02-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_banner_banner_link_banner_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_feature', models.BooleanField(default=False)),
            ],
        ),
    ]
